DIRECTIONS = [
    'FORWARD',
    'LEFT',
    'RIGHT',
    'BACK',
    'DIAGONALLY_UP_LEFT',
    'DIAGONALLY_UP_RIGHT',
    'DIAGONALLY_DOWN_LEFT',
    'DIAGONALLY_DOWN_RIGHT',
    'STOP'
]

MAX_TRIES = 16
